### ISSUE TITLE
fix `DHCP Options` section in `ZTP.md`

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-prov-life#81]
see https://github.com/opiproject/opi-prov-life/blob/main/ZTP.md#dhcp-options
now it's copy-paste from SONiC... we need to change this

**Comment by ballle98** [comment]
https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xhtml

There are several options in Reserved Private Use area not sure why this was used and not vendor options may need to ask developers.

User Class is defined in RFC 3004 and can be 1 or more values describing the client.  The problem is there is no ack from the server that this information was used to give different options.  This is why vendor options would be better.

Looking at https://github.com/sonic-net/SONiC/blob/master/doc/ztp/ztp.md#34-dhcp-options

We can just get rid of 224, 225, 225

<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The use of following DHCP options will be deprecated in future releases of SONiC as its values can be included in the ZTP JSON file whose URL can be obtained via DHCP option 67.</p>

DeprecatedDHCP Options | Name
-- | --
224 | snmp_community
225 | minigraph_url
226 | acl_url


</body>
</html>

**Comment by glimchb** [comment]
thanks @ballle98 
you want to propose PR how final OPI dhcp options look like ?
